baseURL: https://blog.hasiotis.dev
languageCode: en-us
title: Personal website and blog
theme: hugo-refresh

DefaultContentLanguage: en
disableKinds: ["sitemap", "RSS"]
assetDir: public/
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

params:
  articlesPerRow: 3
  favicon: "/images/favicon.svg"
  jsMinify: false
  cssMinify: false
  cssIntegrity: true
  jsIntegrity: true
  mainColour: "#F39200"

  # summary options
  summary:
    # option to specify the default image in the summary list
    # the starting folder is configure in "assetDir" of this file
    defaultImage : "/images/default_summary.jpg"
  # loading options
  loading:
    # option to specify the loading image
    # the starting folder is configure in "assetDir" of this file
    image: "/images/loaders/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Open Sans"

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    # the starting folder is configure in "assetDir" of this file
    logo: "/images/refresh-square.svg"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  navbar:
    fontFamily: "Open Sans"

  # 404 page options
  pagNotFound:
    image: "/images/avataaars_404.png"
    title: 404 Page Not Found :(
    subtitle: This is not the page you were looking for...
    imageWidth: 500px

  homepage:
    linkPosition: "menu"
    title: Nikos Chasiotis
    subtitle: Personal website and blog
    image: "/images/avataaars.png" # worker.svg
    imageWidth: 500px

  footer:
    logo: "/images/refresh-square.svg"
    email:
      link: hasiotis@gmail.com
      title: My Email
    linkedin:
      link: in/hasiotis
      title: My LinkedIn
    github:
      link: hasiotis
      title: Github
    twitter:
       link: hasiotis
       title: Twitter
    copyright: Nikos Chasiotis - 2020
